version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - courseight-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/courseight?authSource=admin
      - SESSION_SECRET=your_secure_random_string
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - courseight-network
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - courseight-network
    restart: unless-stopped

networks:
  courseight-network:
    driver: bridge

volumes:
  mongodb_data: