version: '3.8'

services:
  mongodb:
    image: mongo:latest
    # MongoDB menggunakan image resmi, tidak perlu build

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: sesarafli/courseight-backend:latest
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: sesarafli/courseight-frontend:latest